title: "Meet Patel"
email: pmp0792@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello..,Meet is here from Ahmedabad, India..
baseurl: "/" 
url: "https://meetpatel41011.github.io/" 
twitter_username: mlhacks
github_username:  mlh-fellowship

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg